default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: timbuk3_development

test:
  <<: *default
  database: timbuk3_test

production:
  <<: *default
  database: timbuk3_production
  username: timbuk3
  password: <%= ENV['TIMBUK3_DATABASE_PASSWORD'] %>
